<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9rbzx7g\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9rbzx7g/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9rbzx7g.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9rbzx7g\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9rbzx7g\appProdProjectContainer([
    'container.build_hash' => '9rbzx7g',
    'container.build_id' => '90ccf42e',
    'container.build_time' => 1695202441,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9rbzx7g');
